In [7]:
from scipy.sparse import *
import numpy as np

In [16]:
rows = [3, 2]
cols = [1, 0]
data = [1, 2]

a = coo_matrix((data, (rows, cols)))

In [17]:
print(a.toarray())

[[0 0]
 [0 0]
 [2 0]
 [0 1]]


In [18]:
rows = [3, 2]
cols = [0, 0]
data = [1, 2]

b = coo_matrix((data, (rows, cols)), (4, 2))

In [19]:
print(b.toarray())

[[0 0]
 [0 0]
 [2 0]
 [1 0]]


[[0 0]
 [0 0]
 [4 0]
 [1 1]]


In [24]:
c = a+b

In [25]:
print(c.toarray())

[[0 0]
 [0 0]
 [4 0]
 [1 1]]


In [29]:
c = c.tocoo()
print(type(c))

<class 'scipy.sparse.coo.coo_matrix'>
